## Use Numpy

##### NumPy (Numerical Python) is a fundamental package for scientific computing in Python. <br>It provides support for large, multi-dimensional arrays and matrices, along with a collection of <br>high-level mathematical functions to operate on these arrays efficiently.

In [1]:
# import numpy 
import numpy as np

# display function
def display(*args):
    i = 0
    for arg in args:
        print(f'{arg}' if i%2==0 else f'{arg}\n')
        i+=1


#### Create ndarray

In [2]:
# 1. Create ndarray using python list : [1,2,3,4,5]

array1 = np.array([1, 2, 3, 4, 5])
display("NumPy array:", array1)
type(array1)


NumPy array:
[1 2 3 4 5]



numpy.ndarray

In [3]:
# 2. Create a two-d ndarray. It conains 2 rows and 3 columns

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])
display("2D array:", array2)

type(array2)

2D array:
[[1 2 3]
 [4 5 6]]



numpy.ndarray

In [4]:
# 3. Create a ndarray using arange() 1-5 with data type specified
array3 = np.arange(1, 6, dtype=int)
display("Array using arange:", array3)

Array using arange:
[1 2 3 4 5]



In [5]:
# 4. Create a ndarray with 5 evenly spaced numbers between 0 and 1

array4 = np.linspace(0, 1, 5)
display("Evenly spaced array:", array4)

Evenly spaced array:
[0.   0.25 0.5  0.75 1.  ]



In [6]:
# 5. Create a two-d ndarray using np.diag() - 1,2,3,4 in diagonal position

array5 = np.diag([1, 2, 3, 4])
array6 = np.arange(1, 10).reshape(3, 3)
display("Diagonal array:", array5, "3 × 3 array:", array6)
np.diag(array6, k=-1)

Diagonal array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

3 × 3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([4, 8])

In [7]:
# 6. Create a two-d ndarray with ones on the diagonal line and zeros elsewhere using np.eye()

array6 = np.eye(3)
print(array6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# 7. Create a two-d ndarray with 3 by 3 zeros

array7 = np.zeros((3, 3))
print(array7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# 8. Create a two-d ndarray with 3 by 3 ones

array8 = np.ones((3, 3))
print(array8)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# 9. Create a two-d ndarray with 3 by 3 filled with 7 using np.full()

array9 = np.full((3, 3), 7)
display(array9)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [11]:
# 10. Create a ndarray using np.asarray - use list or tuple

array10 = np.asarray([1, 2, 3, 4, 5])
print(array10)

[1 2 3 4 5]


In [12]:
# 11. Explore ndarray attributes such as shape, dtype, ndim, size, itemsize, nbytes, etc.
array1= np.arange(1,11)
array2 = np.arange(1,11).reshape(2,5)

array1 = np.arange(1, 11)
array2 = np.arange(1, 11).reshape(2, 5)

for arr in (array1, array2):
    print(arr)
    print("Shape:", arr.shape)        # Length along each dimension
    print("Data type:", arr.dtype)    # Type of stored elements
    print("Dimensions:", arr.ndim)    # Number of dimensions
    print("Size:", arr.size)          # Total number of elements
    print("Item size:", arr.itemsize) # Bytes per element
    print("Total bytes:", arr.nbytes) # Bytes used by element data
    print()

[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Dimensions: 1
Size: 10
Item size: 8
Total bytes: 80

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Data type: int64
Dimensions: 2
Size: 10
Item size: 8
Total bytes: 80



#### Access ndarray elements

In [14]:
# 1. Access the a) 5th element b)third to sixth elements c) last 3 items

array1 = np.arange(10)
print(array1)
print(array1[4])
print(array1[2:6])
print(array1[-3:])

[0 1 2 3 4 5 6 7 8 9]
4
[2 3 4 5]
[7 8 9]


In [15]:
array1 = np.arange(10, 101, 10)

print(array1)       # [10 20 30 40 50 60 70 80 90 100]
print(array1[4])    # 50 — пятый элемент
print(array1[2:6])  # [30 40 50 60] — с третьего по шестой
print(array1[-3:])  # [80 90 100] — последние три

[ 10  20  30  40  50  60  70  80  90 100]
50
[30 40 50 60]
[ 80  90 100]


In [16]:
# 2. Access the second row and third column of a two_d ndarray 

array_2d = np.arange(16).reshape(4,4)
print(array_2d)
print(array_2d[1,2])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6


In [17]:
# 3. Reverse the two_d ndarray

array_2d = np.arange(16).reshape(4,4)
print(array_2d)

reversed_array = array_2d[::-1, ::-1]

print(reversed_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


#### Generate Random Numbers

In [42]:
# generate random number to fill the two_d ndarray with 3 rows and 3 columns
# legacy generator

nums = np.random.randint(1,20,(3,2))
print(nums)
print(f"---------------------------")
generator0 = np.random.RandomState(seed=12345)
nums1 = generator0.randint(1,20,(3,2))
print(nums1)

print(f"---------------------------")
array_random = np.random.rand(3, 3)
print(array_random)
print(f"---------------------------")

#modern generator

rng = np.random.default_rng(seed=12345)
nums2 = rng.integers(1,20,(3,2))
print(nums2)


[[17 14]
 [ 1 12]
 [ 1  6]]
---------------------------
[[ 3  6]
 [ 2  5]
 [10  6]]
---------------------------
[[0.22246294 0.45322406 0.57607106]
 [0.74467572 0.30503313 0.04419865]
 [0.46066649 0.7746957  0.26508689]]
---------------------------
[[14  5]
 [15  7]
 [ 4 16]]


#### Advanced indexing

In [44]:
# select specific positions (0,2),(1,1), and (2,0)

array_2d = np.arange(9).reshape(3,3)
print(array_2d)
points = array_2d[[0,1,2],[2,1,0]]
print(points)
print(f"---------------------------")

rows = [0,1,2]
cols = [2,1,0]
new_points = array_2d[rows, cols]
print("\n", new_points)

 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 4 6]
---------------------------

 [2 4 6]


In [45]:
# select all elements greather than 30

rng = np.random.default_rng(123)
array_2d = rng.integers(50,size=(3,3))
print(array_2d)


[[ 0 34 29]
 [ 2 45 11]
 [12  9 16]]


#### Array Broadcasting

In [52]:
rng = np.random.default_rng(seed=123)
matrix = rng.integers(10,50,(3,3))
print(matrix)
print(f"---------------------------")
one_row_matrix = matrix.reshape(1,-1)
one_col_matrix = matrix.reshape(-1,1)
print(f"---------------------------")
display(one_row_matrix, one_col_matrix)
print(f"---------------------------")

combined = one_row_matrix + one_col_matrix
display(one_row_matrix.shape, one_col_matrix.shape,combined)


[[10 37 33]
 [12 46 18]
 [20 17 23]]
---------------------------
---------------------------
[[10 37 33 12 46 18 20 17 23]]
[[10]
 [37]
 [33]
 [12]
 [46]
 [18]
 [20]
 [17]
 [23]]

---------------------------
(1, 9)
(9, 1)

[[20 47 43 22 56 28 30 27 33]
 [47 74 70 49 83 55 57 54 60]
 [43 70 66 45 79 51 53 50 56]
 [22 49 45 24 58 30 32 29 35]
 [56 83 79 58 92 64 66 63 69]
 [28 55 51 30 64 36 38 35 41]
 [30 57 53 32 66 38 40 37 43]
 [27 54 50 29 63 35 37 34 40]
 [33 60 56 35 69 41 43 40 46]]


In [54]:
arry1 = np.array([1,2,3])
arry2 = np.arange(12).reshape(3,4)

display(arry1.shape, arry2.shape)

array_add_col = arry1[:,np.newaxis]
array_add_row = arry1[np.newaxis,:]

# add two arrays

combined = array_add_col + arry2
print(combined)

(3,)
(3, 4)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.arange(12).reshape(4,3)



#### Iterating over arrays

In [55]:
array1 = np.array([1,2,3])
array2 = np.arange(12).reshape(3,4)

for num in array1:
    print(num, end = " ")
print()

#2d

for row in array2:
    for col in row:
        print(col, end = " ")
    print()
print()

#2d using index

for i in range(array2.shape[0]):
    for j in range(array2.shape[1]):
        print(array2[i,j], end = " ")
    print()


1 2 3 
0 1 2 3 
4 5 6 7 
8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 


#### Using concatenate, vstack and hstack

In [57]:
# concatenate 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1,arr2), axis=0))
print(np.concatenate((arr1,arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [59]:
# vstack, hstack

print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Exercise using Consumer.data

In [64]:
# import consumer.csv

consumer_array = np.genfromtxt('ConsumerData.csv',
                               delimiter=',',
                               skip_header=1)

# 1. Display consumer_array attributes such as shape, dtype, ndim, size, itemsize, nbytes, etc.

print(consumer_array.shape, consumer_array.dtype, consumer_array.ndim, consumer_array.size, consumer_array.itemsize, consumer_array.shape)
display(consumer_array)

(50, 5) float64 2 250 8 (50, 5)
[[  1.          62.         113.93269792 323.          19.        ]
 [         nan  65.          94.6391492  430.           1.        ]
 [  3.          18.          67.62001018 677.           8.        ]
 [  4.          21.         159.3620641           nan   0.        ]
 [  5.          21.                  nan          nan   4.        ]
 [  6.          57.         122.3181108  448.          27.        ]
 [  7.          27.          23.38216408 509.          27.        ]
 [  8.          37.         131.17438947 711.          25.        ]
 [  9.          39.         130.17723009          nan   6.        ]
 [ 10.                  nan 131.04811944 358.          21.        ]
 [ 11.          54.                  nan 336.                  nan]
 [ 12.          41.         142.72765384 386.           7.        ]
 [ 13.          24.                  nan          nan  24.        ]
 [ 14.          42.          98.66575168 311.          24.        ]
 [ 15.          

In [66]:
# 2. Display the first 5 rows 
 
print(consumer_array[:5])

[[  1.          62.         113.93269792 323.          19.        ]
 [         nan  65.          94.6391492  430.           1.        ]
 [  3.          18.          67.62001018 677.           8.        ]
 [  4.          21.         159.3620641           nan   0.        ]
 [  5.          21.                  nan          nan   4.        ]]


In [71]:
# 3. Replace nan with 0
new_consumer_array = consumer_array.copy()

nan_cells = np.isnan(new_consumer_array)
print(nan_cells)

new_consumer_array[nan_cells] = 0

[[False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False  True False]
 [False False  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]
 [False  True False False False]
 [False False  True False  True]
 [False False False False False]
 [False False  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False  True False False]
 [False False False False False]
 [False False False  True False]
 [False Fa

In [73]:
# 4. Slice to display only the first 10 rows and first 3 columns

print(new_consumer_array[:10,:3])


[[  1.          62.         113.93269792]
 [  0.          65.          94.6391492 ]
 [  3.          18.          67.62001018]
 [  4.          21.         159.3620641 ]
 [  5.          21.           0.        ]
 [  6.          57.         122.3181108 ]
 [  7.          27.          23.38216408]
 [  8.          37.         131.17438947]
 [  9.          39.         130.17723009]
 [ 10.           0.         131.04811944]]


In [74]:
# 5. Create a boolean mask to display rows where age column is greater than 30 (the 2nd column)
 
age_more_than_30 = new_consumer_array[:,1] > 30
print(new_consumer_array[age_more_than_30])

[[  1.          62.         113.93269792 323.          19.        ]
 [  0.          65.          94.6391492  430.           1.        ]
 [  6.          57.         122.3181108  448.          27.        ]
 [  8.          37.         131.17438947 711.          25.        ]
 [  9.          39.         130.17723009   0.           6.        ]
 [ 11.          54.           0.         336.           0.        ]
 [ 12.          41.         142.72765384 386.           7.        ]
 [ 14.          42.          98.66575168 311.          24.        ]
 [ 15.          42.         145.57361527 607.          15.        ]
 [ 18.          56.         140.71481653 482.           8.        ]
 [ 19.          57.          57.86886099 428.          22.        ]
 [ 20.          41.          43.20673358 575.          15.        ]
 [ 21.          64.          76.77710317 474.          11.        ]
 [ 22.          42.          85.46793877 671.           0.        ]
 [ 23.          35.         122.63541868 484.   

In [ ]:
# 6. Add age column by 2 and display the first 5 rows
 


In [ ]:
# 7. calculate mean age 
 


In [ ]:
# 8. Sort the credit score column (4th column)

sorted = np.sort(new_consumer_array[:,3])
print(sorted)

                  

In [ ]:
# 9. Display the data with credit score > 700


In [ ]:
# 10. Save the file with headers

headers = ['ID','Age','Interest','Credit_Score','Years_with_Bank']
np.savetxt('sorted_credit_score.csv',new_consumer_array,delimiter=',',
           header=','.join(headers),fmt='%f')
print(','.join(headers))