## Use Numpy

##### NumPy (Numerical Python) is a fundamental package for scientific computing in Python. <br>It provides support for large, multi-dimensional arrays and matrices, along with a collection of <br>high-level mathematical functions to operate on these arrays efficiently.

In [2]:
# import numpy 
import numpy as np

# display function
def display(*args):
    i = 0
    for arg in args:
        print(f'{arg}' if i%2==0 else f'{arg}\n')
        i+=1


#### Create ndarray

In [4]:
# 1. Create ndarray using python list : [1,2,3,4,5]

array1 = np.array([1,2,3,4,5])
display(array1)
type(array1)

[1 2 3 4 5]


numpy.ndarray

In [6]:
# 2. Create a two-d ndarray. It conains 2 rows and 3 columns

array_2d = np.array([[1,2,3],[4,5,6]])
display(array_2d)
type(array_2d)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [11]:
# 3. Create a ndarray using arange() 1-5 with data type specified

array1 = np.arange(1,6,2, dtype=int)

display(array1)

[1 2 3 4]


In [14]:
# 4. Create a ndarray with 5 evenly spaced numbers between 0 and 1

array1 = np.linspace(0,1,num=5, endpoint=False)
display(array1)

[0.  0.2 0.4 0.6 0.8]


In [22]:
# 5. Create a two-d ndarray using np.diag() - 1,2,3,4 in diagonal position

array1 = np.diag([1,2,3,4])
array2 = np.arange(1,10).reshape(3,3)
display(array1,array2)
np.diag(array2,k=-1)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([4, 8])

In [23]:
# 6. Create a two-d ndarray with ones on the diagonal line and zeros elsewhere using np.eye()

array1 = np.eye(3,3)
display(array1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 7. Create a two-d ndarray with 3 by 3 zeros

np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
# 8. Create a two-d ndarray with 3 by 3 ones

np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
# 9. Create a two-d ndarray with 3 by 3 filled with 7 using np.full()

array1 = np.full((3,3),7)
display(array1)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [31]:
# 10. Create a ndarray using np.asarray - use list or tuple

np.asarray((1,2,3))

array([1, 2, 3])

In [34]:
# 11. Explore ndarray attributes such as shape, dtype, ndim, size, itemsize, nbytes, etc.
array1= np.arange(1,11)
array2 = np.arange(1,11).reshape(2,5)

display(array1.shape,array1.dtype, array1.ndim, array1.size, array1.itemsize, array1.nbytes) 
display(array2.shape,array2.dtype, array2.ndim, array2.size, array2.itemsize, array2.nbytes) 

(10,)
int64

1
10

8
80

(2, 5)
int64

2
10

8
80



#### Access ndarray elements

In [9]:
# 1. Access the a) 5th element b)third to sixth elements c) last 3 items
import numpy as np

array1 = np.arange(1,11)
print(array1)
print(array1[4])
print(array1[2:6])
print(array1[-3:])

[ 1  2  3  4  5  6  7  8  9 10]
5
[3 4 5 6]
[ 8  9 10]


In [11]:
# 2. Access the second row and third column of a two_d ndarray 

array_2d = np.arange(16).reshape(4,4)
print(array_2d)
print(array_2d[1,2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6


In [13]:
# 3. Reverse the two_d ndarray

array_2d = np.arange(16).reshape(4,4)
print(array_2d)
reversed_array = array_2d[::-1,::-1]
print(reversed_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


#### Generate Random Numbers

In [21]:
# generate random number to fill the two_d ndarray with 3 rows and 3 columns
# legacy generator
nums = np.random.randint(1,20,(3,2))
print(nums)
generator0 = np.random.RandomState(seed=12345)
nums1 = generator0.randint(1,20,(3,2))
print(nums1)
# modern generator
rng = np.random.default_rng(seed=12345)
nums2 = rng.integers(1,20,(3,2))
print(nums2)

[[ 2  6]
 [ 4  7]
 [ 5 18]]
[[ 3  6]
 [ 2  5]
 [10  6]]
[[14  5]
 [15  7]
 [ 4 16]]


#### Advanced indexing

In [26]:
# select specific positions (0,2),(1,1), and (2,0)

array_2d = np.arange(9).reshape(3,3)
print(array_2d)
points = array_2d[[0,1,2],[2,1,0]]
print(points)
rows = [0,1,2]
cols = [2,1,0]
new_points = array_2d[rows,cols]
print("\n",new_points)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 4 6]

 [2 4 6]


In [29]:
# select all elements greather than 30

rng = np.random.default_rng(123)
array_2d = rng.integers(50,size=(3,3))
print(array_2d)
greater_than_30 = array_2d > 30
print(greater_than_30)
print(array_2d[greater_than_30])

[[ 0 34 29]
 [ 2 45 11]
 [12  9 16]]
[[False  True False]
 [False  True False]
 [False False False]]
[34 45]


#### Array Broadcasting

In [30]:
rng = np.random.default_rng(seed=123)
matrix = rng.integers(10,51,(3,3))
print(matrix)
one_row_matrix = matrix.reshape(1,-1)
one_col_matrix = matrix.reshape(-1,1)
display(one_row_matrix, one_col_matrix)

combined = one_row_matrix + one_col_matrix
display(one_row_matrix.shape, one_col_matrix.shape,combined)


[[10 37 34]
 [12 47 19]
 [20 17 23]]


array([[10, 37, 34, 12, 47, 19, 20, 17, 23]])

array([[10],
       [37],
       [34],
       [12],
       [47],
       [19],
       [20],
       [17],
       [23]])

(1, 9)

(9, 1)

array([[20, 47, 44, 22, 57, 29, 30, 27, 33],
       [47, 74, 71, 49, 84, 56, 57, 54, 60],
       [44, 71, 68, 46, 81, 53, 54, 51, 57],
       [22, 49, 46, 24, 59, 31, 32, 29, 35],
       [57, 84, 81, 59, 94, 66, 67, 64, 70],
       [29, 56, 53, 31, 66, 38, 39, 36, 42],
       [30, 57, 54, 32, 67, 39, 40, 37, 43],
       [27, 54, 51, 29, 64, 36, 37, 34, 40],
       [33, 60, 57, 35, 70, 42, 43, 40, 46]])

In [ ]:
arry1 = np.array([1,2,3])
arry2 = np.arange(12).reshape(3,4)

display(arry1.shape, arry2.shape)

array_add_col = arry1[:,np.newaxis]
array_add_row = arry1[np.newaxis,:]

# add two arrays
combined = array_add_col + arry2
print(combined)
combined = array_add_row + arry2
print(combined)

In [ ]:
array1 = np.array([1,2,3])
array2 = np.arange(12).reshape(4,3)



#### Iterating over arrays

In [36]:
array1 = np.array([1,2,3])
array2 = np.arange(12).reshape(3,4)

for num in array1:
    print(num, end=' ')
print()
# 2d
for row in array2:
    for col in row:
        print(col, end=' ')
    print()
print('\n')
# 2d using index
for i in range(array2.shape[0]):
    for j in range(array2.shape[1]):
        print(array2[i,j], end= ' ')
    print()

1 2 3 
0 1 2 3 
4 5 6 7 
8 9 10 11 


0 1 2 3 
4 5 6 7 
8 9 10 11 


#### Using concatenate, vstack and hstack

In [39]:
# concatenate 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
# vstack, hstack
print(np.vstack((arr1,arr2)))

print(np.hstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Exercise using Consumer.data

In [3]:
# import consumer.csv
import numpy as np
consumer_array = np.genfromtxt('ConsumerData.csv',
                               delimiter=',',
                               skip_header=1)

# 1. Display consumer_array attributes such as shape, dtype, ndim, size, itemsize, nbytes, etc.
print(consumer_array.shape,consumer_array.dtype,consumer_array.ndim,consumer_array.size, 
      consumer_array.itemsize,consumer_array.nbytes)
display(consumer_array)

(50, 5) float64 2 250 8 2000
[[  1.          62.         113.93269792 323.          19.        ]
 [         nan  65.          94.6391492  430.           1.        ]
 [  3.          18.          67.62001018 677.           8.        ]
 [  4.          21.         159.3620641           nan   0.        ]
 [  5.          21.                  nan          nan   4.        ]
 [  6.          57.         122.3181108  448.          27.        ]
 [  7.          27.          23.38216408 509.          27.        ]
 [  8.          37.         131.17438947 711.          25.        ]
 [  9.          39.         130.17723009          nan   6.        ]
 [ 10.                  nan 131.04811944 358.          21.        ]
 [ 11.          54.                  nan 336.                  nan]
 [ 12.          41.         142.72765384 386.           7.        ]
 [ 13.          24.                  nan          nan  24.        ]
 [ 14.          42.          98.66575168 311.          24.        ]
 [ 15.          42.

In [45]:
# 2. Display the first 5 rows 
 
print(consumer_array[:5])

[[  1.          62.         113.93269792 323.          19.        ]
 [         nan  65.          94.6391492  430.           1.        ]
 [  3.          18.          67.62001018 677.           8.        ]
 [  4.          21.         159.3620641           nan   0.        ]
 [  5.          21.                  nan          nan   4.        ]]


In [ ]:
# 3. Replace nan with 0
new_consumer_array = consumer_array.copy()

nan_cells = np.isnan(new_consumer_array)
#print(nan_cells)
#new_consumer_array[nan_cells]
new_consumer_array[nan_cells] = 0
print(new_consumer_array)

In [7]:
# 4. Slice to display only the first 10 rows and first 3 columns

print(new_consumer_array[:10,:3])

[[  1.          62.         113.93269792]
 [  0.          65.          94.6391492 ]
 [  3.          18.          67.62001018]
 [  4.          21.         159.3620641 ]
 [  5.          21.           0.        ]
 [  6.          57.         122.3181108 ]
 [  7.          27.          23.38216408]
 [  8.          37.         131.17438947]
 [  9.          39.         130.17723009]
 [ 10.           0.         131.04811944]]


In [ ]:
# 5. Create a boolean mask to display rows where age column is greater than 30 (the 2nd column)
 
age_more_than_30 = new_consumer_array[:,1] > 30
print(new_consumer_array[age_more_than_30])

In [9]:
# 6. Add age column by 2 and display the first 5 rows
new_consumer_array[:,1] += 2
print(new_consumer_array[:5])


[[  1.          64.         113.93269792 323.          19.        ]
 [  0.          67.          94.6391492  430.           1.        ]
 [  3.          20.          67.62001018 677.           8.        ]
 [  4.          23.         159.3620641    0.           0.        ]
 [  5.          23.           0.           0.           4.        ]]


In [11]:
# 7. calculate mean age 
 
mean_age = np.mean(new_consumer_array[:,1])
std_age = np.std(new_consumer_array[:,1])
display('Mean age:',mean_age, 'std age:',std_age)

Mean age:
40.58

std age:
17.625084396961054



In [ ]:
# 8. Sort the credit score column (4th column) # [::-1] reverse order, descending order
'''
sorted = np.sort(new_consumer_array[:,3])
#sorted = -np.sort(-new_consumer_array[:,3]) # reverse order, descending order
print(sorted)       
'''
sorted_indice = np.argsort(new_consumer_array[:,3]) # -ndarray will display descending order
print(sorted_indice)
sorted_credit = new_consumer_array[sorted_indice]
print(sorted_credit)

In [24]:
# 9. Display the data with credit score > 700

high_credit = new_consumer_array[:,3] > 700
print(high_credit)
print(new_consumer_array[high_credit])

high_credit_1 = np.where(new_consumer_array[:,3] > 700)
new_consumer_array[high_credit_1]

[False False False False False False False  True False False False False
 False False False False False False False False False False False  True
  True False False  True False False False False False False  True  True
 False False False False False  True  True False False False False  True
 False  True]
[[  8.          39.         131.17438947 711.          25.        ]
 [ 24.          57.          98.94827242 744.           0.        ]
 [ 25.          45.         197.90729085 788.          25.        ]
 [ 28.          29.           0.         815.          12.        ]
 [ 35.          67.         138.1393261  710.           3.        ]
 [ 36.          20.          44.87293124 750.          10.        ]
 [ 42.          49.          37.29771342 761.          29.        ]
 [  0.          39.         195.7627037  828.           5.        ]
 [ 48.          21.          27.05380261 764.           0.        ]
 [ 50.          52.          41.63538102 745.          10.        ]]


array([[  8.        ,  39.        , 131.17438947, 711.        ,
         25.        ],
       [ 24.        ,  57.        ,  98.94827242, 744.        ,
          0.        ],
       [ 25.        ,  45.        , 197.90729085, 788.        ,
         25.        ],
       [ 28.        ,  29.        ,   0.        , 815.        ,
         12.        ],
       [ 35.        ,  67.        , 138.1393261 , 710.        ,
          3.        ],
       [ 36.        ,  20.        ,  44.87293124, 750.        ,
         10.        ],
       [ 42.        ,  49.        ,  37.29771342, 761.        ,
         29.        ],
       [  0.        ,  39.        , 195.7627037 , 828.        ,
          5.        ],
       [ 48.        ,  21.        ,  27.05380261, 764.        ,
          0.        ],
       [ 50.        ,  52.        ,  41.63538102, 745.        ,
         10.        ]])

In [25]:
# 10. Save the file with headers

headers = ['ID','Age','Interest','Credit_Score','Years_with_Bank']
np.savetxt('sorted_credit_score.csv',new_consumer_array,delimiter=',',
           header=','.join(headers),fmt='%f')
print(','.join(headers))

ID,Age,Interest,Credit_Score,Years_with_Bank
